### ISSUE TITLE
features: todo

### ISSUE THREAD

**Issue by 0xFireball** [0xFireball/nspire-nd#1]
- [x] core
  - [x] framerate-independent
  - [x] max-size groups
  - [x] state/switching system
  - [x] sprites
    - [x] makeGraphic
    - [x] loadGraphic
    - [x] rotation
    - [x] KinematicSprite
- [ ] perf
  - [ ] graphic caching
- [ ] tilemap
  - [ ] basic array-tilemap rendering
  - [ ] tilemap collision
- [ ] text
  - [ ] cross-plaform text with nSDL on Nspire and SDL_ttf on desktop
- [ ] ui
  - [ ] basic menu ui
- [ ] collision
  - [x] AABB overlap
  - [x] quadtree
  - [ ] collision groups
  - [ ] collision layers
- [ ] camera
  - [x] basic camera and translation
  - [ ] multiple cameras
- [ ] particles
  - [x] basic particle emitter
  - [ ] particles with custom property ranges
  - [ ] custom particle textures
